/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.Course.CourseController;
import com.mycompany.projectmanagementsystem.GeneralFunction.FileHandler;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class admin_view_course extends javax.swing.JFrame {

    String[] courseRecord;
    
    /**
     * Creates new form admin_register_course
     */
    public admin_view_course() {
        initComponents();
        setIconImage();
        
    }
    
    
    
    public String[] displayCourseDetails(String[] courseDetails){
        
        courseRecord = courseDetails;
        ArrayList<String> list = new ArrayList();
        for (String detail : courseDetails) {
        list.add(detail);
    }
        
        
        school_wise.setText(list.get(2));
        course_name.setText(list.get(1));
        course_code.setText(list.get(0));
        
        
        return courseRecord;
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reg_course_title = new javax.swing.JLabel();
        school_wise_title = new javax.swing.JLabel();
        course_name_title = new javax.swing.JLabel();
        course_name = new javax.swing.JTextField();
        course_code_title = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        school_wise = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New Course");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_course_title.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        reg_course_title.setForeground(new java.awt.Color(2, 50, 99));
        reg_course_title.setText("Course Details");
        getContentPane().add(reg_course_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        school_wise_title.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        school_wise_title.setForeground(new java.awt.Color(2, 50, 99));
        school_wise_title.setText("School Wise");
        getContentPane().add(school_wise_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        course_name_title.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        course_name_title.setForeground(new java.awt.Color(2, 50, 99));
        course_name_title.setText("Course Name");
        getContentPane().add(course_name_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        course_name.setEditable(false);
        course_name.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        course_name.setForeground(new java.awt.Color(2, 50, 99));
        course_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_nameActionPerformed(evt);
            }
        });
        getContentPane().add(course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 270, 40));

        course_code_title.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        course_code_title.setForeground(new java.awt.Color(2, 50, 99));
        course_code_title.setText("Course Code");
        getContentPane().add(course_code_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        course_code.setEditable(false);
        course_code.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        course_code.setForeground(new java.awt.Color(2, 50, 99));
        getContentPane().add(course_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 270, 40));

        jButton2.setBackground(new java.awt.Color(2, 50, 99));
        jButton2.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        school_wise.setEditable(false);
        school_wise.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        school_wise.setForeground(new java.awt.Color(2, 50, 99));
        school_wise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                school_wiseActionPerformed(evt);
            }
        });
        getContentPane().add(school_wise, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 270, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(500, 300));
        background.setMinimumSize(new java.awt.Dimension(500, 300));
        background.setOpaque(true);
        background.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 50, 99));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jLabel1.setText("BACK");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void course_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_nameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void school_wiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_school_wiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_school_wiseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_view_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_view_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_view_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_view_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_view_course().setVisible(true);
            }
        });
    }
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField course_code;
    private javax.swing.JLabel course_code_title;
    private javax.swing.JTextField course_name;
    private javax.swing.JLabel course_name_title;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel reg_course_title;
    private javax.swing.JTextField school_wise;
    private javax.swing.JLabel school_wise_title;
    // End of variables declaration//GEN-END:variables
}
