/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import java.awt.Toolkit;

/**
 *
 * @author ASUS
 */
public class admin_register_course extends javax.swing.JFrame {

    /**
     * Creates new form admin_register_course
     */
    public admin_register_course() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reg_course_title = new javax.swing.JLabel();
        school_wise_title = new javax.swing.JLabel();
        school_wise = new javax.swing.JComboBox<>();
        course_name_title = new javax.swing.JLabel();
        course_name = new javax.swing.JTextField();
        course_code_title = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New Course");
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_course_title.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        reg_course_title.setForeground(new java.awt.Color(2, 50, 99));
        reg_course_title.setText("Register New Course");
        getContentPane().add(reg_course_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        school_wise_title.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        school_wise_title.setForeground(new java.awt.Color(2, 50, 99));
        school_wise_title.setText("School Wise");
        getContentPane().add(school_wise_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        school_wise.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        school_wise.setForeground(new java.awt.Color(2, 50, 99));
        school_wise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(school_wise, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 270, 40));

        course_name_title.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        course_name_title.setForeground(new java.awt.Color(2, 50, 99));
        course_name_title.setText("Course Name");
        getContentPane().add(course_name_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        course_name.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        course_name.setForeground(new java.awt.Color(2, 50, 99));
        course_name.setText("jTextField1");
        course_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_nameActionPerformed(evt);
            }
        });
        getContentPane().add(course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 270, 40));

        course_code_title.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        course_code_title.setForeground(new java.awt.Color(2, 50, 99));
        course_code_title.setText("Course Code");
        getContentPane().add(course_code_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        course_code.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        course_code.setForeground(new java.awt.Color(2, 50, 99));
        course_code.setText("jTextField1");
        getContentPane().add(course_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 270, 40));

        jButton1.setBackground(new java.awt.Color(76, 127, 174));
        jButton1.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(2, 50, 99));
        jButton1.setText("SUBMIT");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(500, 300));
        background.setMinimumSize(new java.awt.Dimension(500, 300));
        background.setOpaque(true);
        background.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void course_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_register_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_register_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_register_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_register_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_register_course().setVisible(true);
            }
        });
    }
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField course_code;
    private javax.swing.JLabel course_code_title;
    private javax.swing.JTextField course_name;
    private javax.swing.JLabel course_name_title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel reg_course_title;
    private javax.swing.JComboBox<String> school_wise;
    private javax.swing.JLabel school_wise_title;
    // End of variables declaration//GEN-END:variables
}
