/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.Assessment.LecReportTableActionEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

public class lect_ReportPanelAction extends javax.swing.JPanel {


    public lect_ReportPanelAction() {
        initComponents();
    }

    public class rPanelActionRenderer extends DefaultTableCellRenderer {
        
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component com = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            lect_ReportPanelAction action = new lect_ReportPanelAction();
            if (isSelected == false && row % 2 == 0) {
                action.setBackground(Color.WHITE);
            } else {
                action.setBackground(com.getBackground());
            }
            return action;

        }
    }
        
    public class TableActionCellEditor extends DefaultCellEditor {
        private LecReportTableActionEvent event;
        public TableActionCellEditor(LecReportTableActionEvent event) {
            super(new JCheckBox());
            this.event = event;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            lect_ReportPanelAction action = new lect_ReportPanelAction();
            action.initEvent(event, row, value);
            action.setBackground(table.getSelectionBackground());
            if (isSelected == true){
                System.out.println(row);
            }
            return action;
        }
    }
        public void initEvent(LecReportTableActionEvent event, int row , Object value) {
            gradeBtn.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent ae) {
                    event.reportGrading(row, value);
                }
            });
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        gradeBtn.setBackground(new java.awt.Color(76, 127, 174));
        gradeBtn.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        gradeBtn.setForeground(new java.awt.Color(255, 255, 255));
        gradeBtn.setText("Grade");
        gradeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        gradeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(gradeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeBtnActionPerformed

    }//GEN-LAST:event_gradeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradeBtn;
    // End of variables declaration//GEN-END:variables
}
