/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.GeneralFunction.FileHandler;
import com.mycompany.projectmanagementsystem.GeneralFunction.SessionManager;
import com.mycompany.projectmanagementsystem.User.User;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

/**
 *
 * @author ASUS
 */
public class NotificationPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentNotificationPage
     */
    private final SessionManager sessionManager = SessionManager.getInstance();
    User user = sessionManager.getCurrentUser();
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel message;
    private javax.swing.JLabel date;
    List<JPanel> notifications = new ArrayList<JPanel>();

    public NotificationPage() {
        initComponents();
        setIconImage();
        showNotification();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notification");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new Color(217,217,217,40));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(610, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(610, 420));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 50, 99));
        jLabel7.setText("Notification");
        jLabel7.setMaximumSize(new java.awt.Dimension(275, 47));
        jLabel7.setMinimumSize(new java.awt.Dimension(275, 47));
        jLabel7.setPreferredSize(new java.awt.Dimension(275, 47));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(700, 500));
        background.setMinimumSize(new java.awt.Dimension(700, 500));
        background.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotificationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotificationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotificationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotificationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotificationPage().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    private void showNotification() {
        List<String> data = FileHandler.readFile("notification.txt");
        Collections.reverse(data); // Reverse the list to start from the bottom
        int count = 0; // Counter for the number of notification panels added
        ArrayList<String> array_list = new ArrayList<>();
        boolean notificationsFound = false;
        for (String line : data) {
            if (count >= 6) {
                break;
            }
            String[] list = line.split(";");
            if (user.getUserID().equals(list[1])) {
                notificationPanel = new JPanel();
                notificationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                notificationPanel.setMaximumSize(new java.awt.Dimension(610, 57));
                notificationPanel.setMinimumSize(new java.awt.Dimension(610, 57));

                icon = new JLabel(new javax.swing.ImageIcon(getClass().getResource("/notification_icon.png")));

                message = new JLabel();
                message.setFont(new java.awt.Font("SansSerif", 1, 12));
                message.setForeground(new java.awt.Color(2, 50, 99));
                message.setMaximumSize(new java.awt.Dimension(280, 41));
                message.setMinimumSize(new java.awt.Dimension(280, 41));
                message.setPreferredSize(new java.awt.Dimension(280, 41));
                message.setText(list[2]);

                date = new JLabel();
                date.setFont(new java.awt.Font("SansSerif", 0, 12));
                date.setForeground(new java.awt.Color(2, 50, 99));
                date.setText(list[3]);

                GroupLayout notificationPanelLayout = new GroupLayout(notificationPanel);
                notificationPanel.setLayout(notificationPanelLayout);
                notificationPanelLayout.setHorizontalGroup(
                        notificationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(notificationPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(icon, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(message, GroupLayout.PREFERRED_SIZE, 488, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(58, Short.MAX_VALUE))
                                .addGroup(GroupLayout.Alignment.TRAILING, notificationPanelLayout.createSequentialGroup()
                                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(date, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                );
                notificationPanelLayout.setVerticalGroup(
                        notificationPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(notificationPanelLayout.createSequentialGroup()
                                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(notificationPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(icon)
                                                .addComponent(message, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(date))
                );

                jPanel2.add(notificationPanel);

                notifications.add(notificationPanel);
                count++;
                notificationsFound = true;
            }
        }
        if (!notificationsFound) {
            JLabel noNotificationLabel = new JLabel("No Notification");
            noNotificationLabel.setFont(new java.awt.Font("SansSerif", 1, 16));
            noNotificationLabel.setForeground(new java.awt.Color(2, 50, 99));
            noNotificationLabel.setAlignmentX(Component.CENTER_ALIGNMENT); // Center the label horizontally
            jPanel2.add(Box.createVerticalGlue()); // Add vertical glue to center the label vertically
            jPanel2.add(noNotificationLabel);
            jPanel2.add(Box.createVerticalGlue()); // Add more vertical glue for spacing
        }
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        jPanel2.add(Box.createHorizontalStrut(5));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
