/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.Assessment.AssessmentController;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shuhuilee
 */
public class PM_assessment_edit extends javax.swing.JFrame {

    private final String assessmentType;
    private final String assessmentID;
    private Map<String, String> userIdToNameMap = new HashMap<>();
    PM_assessment_page parentpage;

    public PM_assessment_edit(String assessmentType, String assessmentID, String intakeCode, PM_assessment_page parentpage) {
        initComponents();
        setIconImage();
        String school = getSchoolByIntake(intakeCode);
        populateLecturers(school);
        this.assessmentType = assessmentType;
        this.assessmentID = assessmentID;
        this.parentpage = parentpage;
        assessment_Type();
        ShowLecturers();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void assessment_Type() {
        if (assessmentType.equalsIgnoreCase("internship_report") || assessmentType.equalsIgnoreCase("investigation")) {
            secondmarker_name.setVisible(false);
            second_maker_name.setVisible(false); // Ensure the label is also hidden
        } else {
            secondmarker_name.setVisible(true);
            second_maker_name.setVisible(true); // Ensure the label is also shown
        }
    }

    private String getSchoolByIntake(String intakeCode) {
        String fileName = "intake.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] list = line.split(";");
                if (list[0].trim().equals(intakeCode)) {
                    return list[1].trim(); // School wise
                }
            }
        } catch (IOException ex) {
            System.err.println("Error reading file: " + ex.getMessage());
        }
        return null;
    }

    private void populateLecturers(String school) {
        supervisorName.removeAllItems();
        secondmarker_name.removeAllItems();
        String fileName = "user.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] list = line.split(";");
                if (list.length > 11 && list[10].equalsIgnoreCase("lecturer") && list[11].trim().equalsIgnoreCase(school)) {
                    String userIdAndName = list[0] + " - " + list[1]; // Concatenate user ID and name
                    supervisorName.addItem(userIdAndName);
                    secondmarker_name.addItem(userIdAndName);
                    userIdToNameMap.put(list[0], userIdAndName);
                }
            }
        } catch (IOException ex) {
            System.out.println("Error reading file: " + ex.getMessage());
        }
    }

    private void ShowLecturers() {
        String fileName = "assessment.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] list = line.split(";");
                if (list.length > 3 && list[1].equalsIgnoreCase(assessmentType)) {
                    // Extract supervisor, second marker, and due date from the line
                    String supervisorId = list[4];
                    String secondMarkerId = list[5];
                    String dueDateString = list[3];

                    Date dueDate = new SimpleDateFormat("yyyy-MM-dd").parse(dueDateString);
                    jDateChooser1.setDate(dueDate);

                    // Set supervisor and second marker in JComboBox
                    supervisorName.setSelectedItem(userIdToNameMap.get(supervisorId));
                    secondmarker_name.setSelectedItem(userIdToNameMap.get(secondMarkerId));
                }
            }
        } catch (IOException | ParseException ex) {
            System.out.println("Error reading file: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ec_edit_assessment = new javax.swing.JLabel();
        supervisor_name = new javax.swing.JLabel();
        second_maker_name = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        supervisorName = new javax.swing.JComboBox<>();
        secondmarker_name = new javax.swing.JComboBox<>();
        sava_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit assessment");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ec_edit_assessment.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        ec_edit_assessment.setForeground(new java.awt.Color(2, 50, 99));
        ec_edit_assessment.setText("Edit Assessment");
        getContentPane().add(ec_edit_assessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        supervisor_name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        supervisor_name.setText("Supervisor Name：");
        getContentPane().add(supervisor_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        second_maker_name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        second_maker_name.setText("Second Marker Name ：");
        getContentPane().add(second_maker_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        duedate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        duedate.setText("Duedate：");
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        supervisorName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        supervisorName.setMaximumSize(new java.awt.Dimension(64, 28));
        supervisorName.setMinimumSize(new java.awt.Dimension(64, 28));
        supervisorName.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(supervisorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, -1));

        secondmarker_name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        secondmarker_name.setMaximumSize(new java.awt.Dimension(64, 28));
        secondmarker_name.setMinimumSize(new java.awt.Dimension(64, 28));
        secondmarker_name.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(secondmarker_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 250, -1));

        sava_button.setBackground(new java.awt.Color(76, 127, 174));
        sava_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        sava_button.setForeground(new java.awt.Color(255, 255, 255));
        sava_button.setText("Save");
        sava_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sava_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(sava_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        back_button.setBackground(new java.awt.Color(76, 127, 174));
        back_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sava_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sava_buttonActionPerformed
        // TODO add your handling code here:
        String supervisor;
        String secondMarker;
        String secondMarkerID = "";
        supervisor = (String) supervisorName.getSelectedItem();

        String supervisorID = supervisor.split(" - ")[0];

        if (assessmentType.equals("internship_report") || assessmentType.equals("investigation")) {
            if (supervisor == null) {
                JOptionPane.showMessageDialog(null, "Please select both supervisor and second marker.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            secondMarker = (String) secondmarker_name.getSelectedItem();
            if (supervisor == null || secondMarker == null) {
                JOptionPane.showMessageDialog(null, "Please select both supervisor and second marker.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            secondMarkerID = secondMarker.split(" - ")[0];
            if (supervisorID.equals(secondMarkerID)) {
                JOptionPane.showMessageDialog(null, "Supervisor and second marker cannot be the same person.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        Date dueDate = jDateChooser1.getDate();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDueDate = dateFormat.format(dueDate);

        // Check if the due date is later than the current date
        Calendar currentDate = Calendar.getInstance();
        currentDate.add(Calendar.DAY_OF_MONTH, 2); // Add 2 days
        Date minDueDate = currentDate.getTime();

        if (dueDate.before(minDueDate)) {
            JOptionPane.showMessageDialog(null, "Due date must be at least 2 days later than today.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        AssessmentController controller = new AssessmentController();
        boolean updateSuccessful = controller.assessment_Edit(assessmentID, supervisorID, secondMarkerID, formattedDueDate);

        if (updateSuccessful) {
            JOptionPane.showMessageDialog(null, "Assessment details saved successfully");
            dispose();
            parentpage.setVisible(false);
            PM_assessment_page assessmentPage = new PM_assessment_page(assessmentType);
            assessmentPage.setVisible(true);
        }
    }//GEN-LAST:event_sava_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        PM_assessment_page assessment = new PM_assessment_page(assessmentType);
        assessment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String assessmentType = "type";
                String assessmentID = "ID";
                new PM_assessment_edit(assessmentType, assessmentID, "Intake", null).setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel ec_edit_assessment;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sava_button;
    private javax.swing.JLabel second_maker_name;
    private javax.swing.JComboBox<String> secondmarker_name;
    private javax.swing.JComboBox<String> supervisorName;
    private javax.swing.JLabel supervisor_name;
    // End of variables declaration//GEN-END:variables
}
