/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import java.awt.Toolkit;

/**
 *
 * @author shuhuilee
 */
public class PM_assessment_edit extends javax.swing.JFrame {

    public PM_assessment_edit() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ec_edit_assessment = new javax.swing.JLabel();
        supervisor_name = new javax.swing.JLabel();
        second_maker_name = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit assessment");
        setMaximumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ec_edit_assessment.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        ec_edit_assessment.setForeground(new java.awt.Color(2, 50, 99));
        ec_edit_assessment.setText("Edit Assessment");
        getContentPane().add(ec_edit_assessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        supervisor_name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        supervisor_name.setText("Supervisor Name：");
        getContentPane().add(supervisor_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        second_maker_name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        second_maker_name.setText("Second Marker Name ：");
        getContentPane().add(second_maker_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        duedate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        duedate.setText("Duedate：");
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));

        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox2.setMaximumSize(new java.awt.Dimension(64, 28));
        jComboBox2.setMinimumSize(new java.awt.Dimension(64, 28));
        jComboBox2.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 210, -1));

        jComboBox3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox3.setMaximumSize(new java.awt.Dimension(64, 28));
        jComboBox3.setMinimumSize(new java.awt.Dimension(64, 28));
        jComboBox3.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 210, -1));

        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField5.setMaximumSize(new java.awt.Dimension(64, 28));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 210, -1));

        jButton2.setBackground(new java.awt.Color(76, 127, 174));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jButton3.setBackground(new java.awt.Color(76, 127, 174));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_assessment_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_assessment_edit().setVisible(true);
            }
        });
    }
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel ec_edit_assessment;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel second_maker_name;
    private javax.swing.JLabel supervisor_name;
    // End of variables declaration//GEN-END:variables
}
