/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import javax.swing.table.TableColumnModel;

/**
 *
 * @author shuhuilee
 */
public class PM_cp1_page extends javax.swing.JFrame {

    public PM_cp1_page() {
        initComponents();
        jComboBox1ActionPerformed(null); // Call to populate the JComboBox
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pm_logo_sysco = new javax.swing.JLabel();
        pm_ec_approvement = new javax.swing.JLabel();
        pm_report_status = new javax.swing.JLabel();
        pm_notification = new javax.swing.JLabel();
        pm_profile = new javax.swing.JLabel();
        pm_logout = new javax.swing.JLabel();
        pm_cp1_report = new javax.swing.JLabel();
        pm_cp1_search = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        pm_cp1_table = new javax.swing.JTable();
        pm_cp1_create_button1 = new javax.swing.JButton();
        pm_cp1_back_button2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 73));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 73));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 73));

        pm_logo_sysco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sysco_logo.png"))); // NOI18N

        pm_ec_approvement.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pm_ec_approvement.setText("EC Approvement");

        pm_report_status.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pm_report_status.setText("Report Status");

        pm_notification.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pm_notification.setText("Notification");

        pm_profile.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pm_profile.setText("Profile");

        pm_logout.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        pm_logout.setText("Log out");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pm_logo_sysco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(pm_ec_approvement)
                .addGap(18, 18, 18)
                .addComponent(pm_report_status)
                .addGap(18, 18, 18)
                .addComponent(pm_notification)
                .addGap(18, 18, 18)
                .addComponent(pm_profile)
                .addGap(18, 18, 18)
                .addComponent(pm_logout)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pm_logout)
                            .addComponent(pm_profile)
                            .addComponent(pm_notification)
                            .addComponent(pm_report_status)
                            .addComponent(pm_ec_approvement)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pm_logo_sysco)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pm_cp1_report.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        pm_cp1_report.setText("Capstone Project 1");
        getContentPane().add(pm_cp1_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        pm_cp1_search.setText("search...");
        pm_cp1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm_cp1_searchActionPerformed(evt);
            }
        });
        getContentPane().add(pm_cp1_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 190, -1));

        pm_cp1_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Assessment ID", "Student Intake", "School", "Supervisor Name", "Second Marker Name", "Assessment Status ", "Duedate", "Action"
            }
        ));
        jScrollPane1.setViewportView(pm_cp1_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 970, 470));

        pm_cp1_create_button1.setBackground(new java.awt.Color(76, 127, 174));
        pm_cp1_create_button1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        pm_cp1_create_button1.setForeground(new java.awt.Color(255, 255, 255));
        pm_cp1_create_button1.setText("Create");
        pm_cp1_create_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm_cp1_create_button1ActionPerformed(evt);
            }
        });
        getContentPane().add(pm_cp1_create_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        pm_cp1_back_button2.setBackground(new java.awt.Color(76, 127, 174));
        pm_cp1_back_button2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        pm_cp1_back_button2.setForeground(new java.awt.Color(255, 255, 255));
        pm_cp1_back_button2.setText("Back");
        pm_cp1_back_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pm_cp1_back_button2ActionPerformed(evt);
            }
        });
        getContentPane().add(pm_cp1_back_button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pm_cp1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm_cp1_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pm_cp1_searchActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        // Check if the combo box is empty
        if (jComboBox1.getItemCount() == 0) {
            // Clear the JComboBox
            jComboBox1.removeAllItems();

            // Get the column model
            TableColumnModel columnModel = pm_cp1_table.getColumnModel();
            for (int i = 0; i < columnModel.getColumnCount(); i++) {
                jComboBox1.addItem(columnModel.getColumn(i).getHeaderValue().toString());
            } 
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void pm_cp1_create_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm_cp1_create_button1ActionPerformed
        // TODO add your handling code here:
//        PM_cp1_create_assessment assessment = new PM_cp1_create_assessment();
//        assessment.setVisible(true);
//        this.dispose(); // Close the current frame
    }//GEN-LAST:event_pm_cp1_create_button1ActionPerformed

    private void pm_cp1_back_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pm_cp1_back_button2ActionPerformed
        // TODO add your handling code here:
//        ProjectManagerPage pm = new ProjectManagerPage();
//        pm.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_pm_cp1_back_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_cp1_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_cp1_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_cp1_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_cp1_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_cp1_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pm_cp1_back_button2;
    private javax.swing.JButton pm_cp1_create_button1;
    private javax.swing.JLabel pm_cp1_report;
    private javax.swing.JTextField pm_cp1_search;
    private javax.swing.JTable pm_cp1_table;
    private javax.swing.JLabel pm_ec_approvement;
    private javax.swing.JLabel pm_logo_sysco;
    private javax.swing.JLabel pm_logout;
    private javax.swing.JLabel pm_notification;
    private javax.swing.JLabel pm_profile;
    private javax.swing.JLabel pm_report_status;
    // End of variables declaration//GEN-END:variables
}
