/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.Assessment.AssessmentController;
import com.mycompany.projectmanagementsystem.EC.ECController;
import com.mycompany.projectmanagementsystem.GeneralFunction.FileHandler;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shuhuilee
 */
public class PM_duedate_edit extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    private String assessmentID;
    private String studentID;
    private String dueDate;
    PM_ec_approvement parentpage;

    public PM_duedate_edit(String assessmentID, String studentID, String dueDate, PM_ec_approvement parentpage) {
        initComponents();
        setIconImage();
        this.assessmentID = assessmentID;
        this.studentID = studentID;
        this.dueDate = dueDate;
        this.parentpage = parentpage;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Adjust the format as per your date format in the file

        // Parse the date string to Date object
        Date date = null;
        try {
            String dateString;
            date = dateFormat.parse(dueDate);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        if (date != null) {
            jDateChooser1.setDate(date);
        }

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to return to PM_ec_approvement?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ec_edit_duedate = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        save_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit duedate");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ec_edit_duedate.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        ec_edit_duedate.setForeground(new java.awt.Color(2, 50, 99));
        ec_edit_duedate.setText("Edit Duedate");
        getContentPane().add(ec_edit_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        duedate.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        duedate.setForeground(new java.awt.Color(2, 50, 99));
        duedate.setText("Duedate:");
        getContentPane().add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, 30));

        save_button.setBackground(new java.awt.Color(76, 127, 174));
        save_button.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setText("Save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 300));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
        String[] assessmentInput = new String[3];
        assessmentInput[0] = studentID;
        assessmentInput[1] = assessmentID;
        Date selectedDate = jDateChooser1.getDate();
        SimpleDateFormat dateTimeFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateTimeText = dateTimeFormat.format(selectedDate);
        assessmentInput[2] = dateTimeText;
        AssessmentController action = new AssessmentController();
        boolean result =  action.editDueDate(assessmentInput);
        if (result) {
            JOptionPane.showMessageDialog(null, "Successfully edit the student due date");
            this.setVisible(false);
            parentpage.loadDataFromFiles();
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_duedate_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_duedate_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_duedate_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_duedate_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String assessmentID = "";
                String studentID = "";
                new PM_duedate_edit(assessmentID, studentID, "", null).setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel ec_edit_duedate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables
}
