/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.EC.ECApprTableActionEvent;
import com.mycompany.projectmanagementsystem.GeneralFunction.FileHandler;
import com.mycompany.projectmanagementsystem.GeneralFunction.SessionManager;
import com.mycompany.projectmanagementsystem.User.User;
import com.mycompany.projectmanagementsystem.User.UserController;
import java.awt.Toolkit;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shuhuilee
 */
public class PM_ec_approvement extends javax.swing.JFrame {

    private final SessionManager sessionManager = SessionManager.getInstance();
    User user = sessionManager.getCurrentUser();

    /**
     * Creates new form ProjectManagerPage
     */
    public PM_ec_approvement() {
        initComponents();
        setIconImage();
        loadDataFromFiles();

        PM_ECActionPanel panel = new PM_ECActionPanel();
        ECApprTableActionEvent event = new ECApprTableActionEvent() {
            @Override
            public void ecEdit(int row, Object value) {
                DefaultTableModel model = (DefaultTableModel) pm_ec_approvement_table.getModel();
                String assessmentID = (String) model.getValueAt(row, 1);
                String studentID = (String) model.getValueAt(row, 2);
                String dueDate = (String) model.getValueAt(row, 4);
                redirectPage(assessmentID, studentID, dueDate);
            }
        };
        pm_ec_approvement_table.getColumnModel().getColumn(5).setCellRenderer(panel.new rPanelActionRenderer());
        pm_ec_approvement_table.getColumnModel().getColumn(5).setCellEditor(panel.new TableActionCellEditor(event));
    }

    void loadDataFromFiles() {
        DefaultTableModel model = (DefaultTableModel) pm_ec_approvement_table.getModel();
        model.setRowCount(0);
        String ecFilePath = "ec.txt";
        String studentAssessmentFilePath = "student_assessment.txt";
        List<String> data = FileHandler.readFile("ec.txt");
        List<String> studentAdata = FileHandler.readFile("student_assessment.txt");
        for (String line : data) {
            String[] list = line.split(";");
            if (list[5].equals("approved")) {
                for (String sALine : studentAdata) {
                    String[] SAList = sALine.split(";");
                    if (SAList[1].equals(list[1]) && SAList[2].equals(list[2])) {
                        model.insertRow(0, new Object[]{
                            list[0],
                            SAList[2],
                            list[1],
                            list[5],
                            SAList[3],
                            null});
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pm_ec_approvement_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pm_logo_sysco = new javax.swing.JLabel();
        pm_ec_approvement = new javax.swing.JLabel();
        pm_notification = new javax.swing.JLabel();
        pm_profile = new javax.swing.JLabel();
        pm_logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Manager EC Aprovement");
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel8.setText("EC Approvement");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pm_ec_approvement_table.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        pm_ec_approvement_table.setForeground(new java.awt.Color(2, 50, 99));
        pm_ec_approvement_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EC ID ", "Assessmnet ID", "Student ID", "Status", "Duedate", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pm_ec_approvement_table.setRowHeight(30);
        jScrollPane1.setViewportView(pm_ec_approvement_table);
        if (pm_ec_approvement_table.getColumnModel().getColumnCount() > 0) {
            pm_ec_approvement_table.getColumnModel().getColumn(5).setMinWidth(140);
            pm_ec_approvement_table.getColumnModel().getColumn(5).setPreferredWidth(140);
            pm_ec_approvement_table.getColumnModel().getColumn(5).setMaxWidth(140);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 960, 470));

        jPanel1.setBackground(new Color(255, 255, 255, 90));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 73));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 73));

        pm_logo_sysco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sysco_logo.png"))); // NOI18N
        pm_logo_sysco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pm_logo_sysco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pm_logo_syscoMouseClicked(evt);
            }
        });

        pm_ec_approvement.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pm_ec_approvement.setForeground(new java.awt.Color(2, 50, 99));
        pm_ec_approvement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pm_ec_approvement.setText("EC Approvement");
        pm_ec_approvement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pm_notification.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pm_notification.setForeground(new java.awt.Color(2, 50, 99));
        pm_notification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pm_notification.setText("Notification");
        pm_notification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pm_notification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pm_notificationMouseClicked(evt);
            }
        });

        pm_profile.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pm_profile.setForeground(new java.awt.Color(2, 50, 99));
        pm_profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pm_profile.setText("Profile");
        pm_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pm_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pm_profileMouseClicked(evt);
            }
        });

        pm_logout.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        pm_logout.setForeground(new java.awt.Color(2, 50, 99));
        pm_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pm_logout.setText("Log Out");
        pm_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pm_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pm_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pm_logo_sysco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(pm_ec_approvement)
                .addGap(18, 18, 18)
                .addComponent(pm_notification)
                .addGap(18, 18, 18)
                .addComponent(pm_profile)
                .addGap(26, 26, 26)
                .addComponent(pm_logout)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pm_logout)
                            .addComponent(pm_profile)
                            .addComponent(pm_notification)
                            .addComponent(pm_ec_approvement)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(pm_logo_sysco)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pm_logo_syscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_logo_syscoMouseClicked
        // TODO add your handling code here:
        ProjectManagerPage pm = new ProjectManagerPage();
        pm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pm_logo_syscoMouseClicked

    private void pm_notificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_notificationMouseClicked
        // TODO add your handling code here:
        NotificationPage noti = new NotificationPage();
        noti.setVisible(true);
    }//GEN-LAST:event_pm_notificationMouseClicked

    private void pm_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_profileMouseClicked
        // TODO add your handling code here:
        PM_profile_page profile = new PM_profile_page();
        profile.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pm_profileMouseClicked

    private void pm_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        UserController action = new UserController();
        action.userLogout();
    }//GEN-LAST:event_pm_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_ec_approvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_ec_approvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_ec_approvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_ec_approvement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_ec_approvement().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    private void redirectPage(String ecID, String studentID, String dueDate) {
        PM_duedate_edit editPage = new PM_duedate_edit(ecID, studentID, dueDate, this);
        editPage.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pm_ec_approvement;
    private javax.swing.JTable pm_ec_approvement_table;
    private javax.swing.JLabel pm_logo_sysco;
    private javax.swing.JLabel pm_logout;
    private javax.swing.JLabel pm_notification;
    private javax.swing.JLabel pm_profile;
    // End of variables declaration//GEN-END:variables
}
