/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectmanagementsystem;

import com.mycompany.projectmanagementsystem.GeneralFunction.SessionManager;
import com.mycompany.projectmanagementsystem.User.Student;
import com.mycompany.projectmanagementsystem.User.User;
import com.mycompany.projectmanagementsystem.User.UserController;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class StudentProfilePage extends javax.swing.JFrame {

    /**
     * Creates new form StudentProfilePage
     */
    private final SessionManager sessionManager = SessionManager.getInstance();
    User user = sessionManager.getCurrentUser();

    public StudentProfilePage() {
        initComponents();
        setIconImage();
        saveBtn.setVisible(false);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        ID.setText(user.getUserID());
        name.setText(user.getName());
        gender.setText(user.getGender());
        intake.setText(((Student) user).getIntakeCode());
        nationality.setText(user.getNationality());
        DOB.setText(dateFormat.format(user.getDateOfBirth()));
        identity.setText(user.getIdentityNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        studentHeader = new javax.swing.JPanel();
        studentLogo = new javax.swing.JLabel();
        studentEcSubmission = new javax.swing.JLabel();
        studentNotification = new javax.swing.JLabel();
        studentProfile = new javax.swing.JLabel();
        studentLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField(user.getEmail());
        numberField = new javax.swing.JTextField(user.getPhoneNumber());
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea(user.getAddress());
        passwordField = new javax.swing.JPasswordField(user.getPassword());
        jPanel2 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        intake = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        nationality = new javax.swing.JLabel();
        identity = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Profile");
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 50, 99));
        jLabel1.setText("Profile Page");
        jLabel1.setMaximumSize(new java.awt.Dimension(206, 38));
        jLabel1.setMinimumSize(new java.awt.Dimension(206, 38));
        jLabel1.setPreferredSize(new java.awt.Dimension(206, 38));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 95, -1, -1));

        editBtn.setBackground(new java.awt.Color(27, 61, 96));
        editBtn.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 100, 40));

        studentHeader.setBackground(new Color(255, 255, 255, 90));
        studentHeader.setToolTipText("");
        studentHeader.setMaximumSize(new java.awt.Dimension(1000, 73));
        studentHeader.setMinimumSize(new java.awt.Dimension(1000, 73));

        studentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sysco_logo.png"))); // NOI18N
        studentLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLogoMouseClicked(evt);
            }
        });

        studentEcSubmission.setBackground(new Color(255, 255, 255, 0));
        studentEcSubmission.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        studentEcSubmission.setForeground(new java.awt.Color(2, 50, 99));
        studentEcSubmission.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentEcSubmission.setText("EC Submission");
        studentEcSubmission.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentEcSubmission.setMaximumSize(new java.awt.Dimension(96, 73));
        studentEcSubmission.setMinimumSize(new java.awt.Dimension(96, 73));
        studentEcSubmission.setPreferredSize(new java.awt.Dimension(96, 73));
        studentEcSubmission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentEcSubmissionMouseClicked(evt);
            }
        });

        studentNotification.setBackground(new Color(255, 255, 255, 0));
        studentNotification.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        studentNotification.setForeground(new java.awt.Color(2, 50, 99));
        studentNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentNotification.setText("Notification");
        studentNotification.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentNotification.setMaximumSize(new java.awt.Dimension(96, 73));
        studentNotification.setMinimumSize(new java.awt.Dimension(96, 73));
        studentNotification.setPreferredSize(new java.awt.Dimension(96, 73));

        studentProfile.setBackground(new Color(255, 255, 255, 0));
        studentProfile.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        studentProfile.setForeground(new java.awt.Color(2, 50, 99));
        studentProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentProfile.setText("Profile");
        studentProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentProfile.setMaximumSize(new java.awt.Dimension(96, 73));
        studentProfile.setMinimumSize(new java.awt.Dimension(96, 73));
        studentProfile.setPreferredSize(new java.awt.Dimension(96, 73));

        studentLogout.setBackground(new Color(255, 255, 255, 0));
        studentLogout.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        studentLogout.setForeground(new java.awt.Color(2, 50, 99));
        studentLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLogout.setText("Log Out");
        studentLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentLogout.setMaximumSize(new java.awt.Dimension(96, 73));
        studentLogout.setMinimumSize(new java.awt.Dimension(96, 73));
        studentLogout.setPreferredSize(new java.awt.Dimension(96, 73));
        studentLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout studentHeaderLayout = new javax.swing.GroupLayout(studentHeader);
        studentHeader.setLayout(studentHeaderLayout);
        studentHeaderLayout.setHorizontalGroup(
            studentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(studentEcSubmission, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(studentNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentHeaderLayout.setVerticalGroup(
            studentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentHeaderLayout.createSequentialGroup()
                .addGroup(studentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentEcSubmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(studentHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(studentLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(studentHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new Color(217,217,217,40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 50, 99));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Personal Information");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 50, 99));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Password:");

        saveBtn.setBackground(new java.awt.Color(27, 61, 96));
        saveBtn.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 50, 99));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Email:");

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(2, 50, 99));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Phone Number:");

        emailField.setEditable(false);
        emailField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(2, 50, 99));
        emailField.setMaximumSize(new java.awt.Dimension(230, 30));
        emailField.setMinimumSize(new java.awt.Dimension(230, 30));
        emailField.setPreferredSize(new java.awt.Dimension(230, 30));

        numberField.setEditable(false);
        numberField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        numberField.setForeground(new java.awt.Color(2, 50, 99));
        numberField.setMaximumSize(new java.awt.Dimension(230, 30));
        numberField.setMinimumSize(new java.awt.Dimension(230, 30));
        numberField.setPreferredSize(new java.awt.Dimension(230, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 50, 99));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Address:");

        addressField.setEditable(false);
        addressField.setColumns(20);
        addressField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addressField.setForeground(new java.awt.Color(2, 50, 99));
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        passwordField.setEditable(false);
        passwordField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(2, 50, 99));
        passwordField.setMaximumSize(new java.awt.Dimension(230, 30));
        passwordField.setMinimumSize(new java.awt.Dimension(230, 30));
        passwordField.setPreferredSize(new java.awt.Dimension(230, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(numberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 590, 490));

        jPanel2.setBackground(new Color(217,217,217,40));

        name.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(2, 50, 99));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Name");

        intake.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        intake.setForeground(new java.awt.Color(2, 50, 99));
        intake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intake.setText("Intake");

        ID.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(2, 50, 99));
        ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID.setText("ID");

        gender.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(2, 50, 99));
        gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender.setText("Gender");

        nationality.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nationality.setForeground(new java.awt.Color(2, 50, 99));
        nationality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nationality.setText("Nationality");

        identity.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        identity.setForeground(new java.awt.Color(2, 50, 99));
        identity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        identity.setText("I/C Number/Passport Number");

        DOB.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DOB.setForeground(new java.awt.Color(2, 50, 99));
        DOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DOB.setText("DOB");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile_icon.png"))); // NOI18N
        jLabel22.setText("jLabel22");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(intake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nationality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(identity, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intake, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 300, 490));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLogoMouseClicked
        StudentDashboardPage dashboard = new StudentDashboardPage();
        dashboard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_studentLogoMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String[] userInput = new String[5];
        userInput[0] = user.getUserID();
        userInput[1] = addressField.getText();
        userInput[2] = emailField.getText();
        userInput[3] = numberField.getText();
        userInput[4] = passwordField.getText();
        UserController action = new UserController();
        boolean result = action.userProfileUpdate(userInput);
        if (result) {
            JOptionPane.showMessageDialog(null, "Successfully change your profile information");
            editBtn.setVisible(true);
            saveBtn.setVisible(false);
            addressField.setEditable(false);
            emailField.setEditable(false);
            numberField.setEditable(false);
            passwordField.setEditable(false);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        editBtn.setVisible(false);
        saveBtn.setVisible(true);
        addressField.setEditable(true);
        emailField.setEditable(true);
        numberField.setEditable(true);
        passwordField.setEditable(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void studentEcSubmissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentEcSubmissionMouseClicked
        StudentEcSubmissionPage ecPage = new StudentEcSubmissionPage();
        ecPage.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_studentEcSubmissionMouseClicked

    private void studentLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLogoutMouseClicked
        this.setVisible(false);
        UserController action = new UserController();
        action.userLogout();
    }//GEN-LAST:event_studentLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentProfilePage().setVisible(true);
        });
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Sysco_icon_with_background.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel ID;
    private javax.swing.JTextArea addressField;
    private javax.swing.JLabel background;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel identity;
    private javax.swing.JLabel intake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nationality;
    private javax.swing.JTextField numberField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel studentEcSubmission;
    private javax.swing.JPanel studentHeader;
    private javax.swing.JLabel studentLogo;
    private javax.swing.JLabel studentLogout;
    private javax.swing.JLabel studentNotification;
    private javax.swing.JLabel studentProfile;
    // End of variables declaration//GEN-END:variables
}
